### ISSUE TITLE
Remove duplicate descriptions

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap.prototype#104]
Some resources are described by multiple documents, e.g. http://api.lobid.org/oer?q=%22Unisul%20Virtual%22 which returns two descriptions for http://lobid.org/oer/b9d9e002-645e-4700-800a-b6f2b71bc004#!

**Comment by fsteeg** [comment]
Fixed in production: http://api.lobid.org/oer?q=%22Unisul%20Virtual%22

Was related to the additional trailing slash (https://github.com/hbz/oerworldmap/issues/81#issuecomment-40585422), which we thought was fixed, but the faulty documents were not replaced (the geonames ID is the parent for the OER resource, and Elasticsearch treats documents with identical IDs but different parents as separate documents).
