### ISSUE TITLE
Fix multiple properties

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap.prototype#105]
Resources such as [1] contain bugs:
- It is typed as both, `schema:Organization` and `schema:Service`
- It contains multiple links to addresses, some of which are not described and some of which contain latitude and longitude. There should be exactly one address.

[2] is lacking geo coordinates.

[1] http://lobid.org/oer/b9d9e002-645e-4700-800a-b6f2b71bc004#!
[2] http://lobid.org/oer/88feda8d-73bc-4b26-84be-f39687c31a04#!

**Comment by literarymachine** [comment]
While reviewing the map I found out that all of these resources share the same problems:
- They have two types
- They have two addresses, one containing the `addressCountry` and one containing the `addressLocality`
- They have two geo coordinates, one of which is falsely typed `geo:coordinate`

Just in case its helpful:

```
http://lobid.org/oer/49b35e71-3260-45de-af75-13f9916bca1f#!
http://lobid.org/oer/1b25cbaa-00ac-46ff-9e96-be00feb10ed4#!
http://lobid.org/oer/23a86495-9a13-4beb-be34-59de1784dfd7#!
http://lobid.org/oer/88feda8d-73bc-4b26-84be-f39687c31a04#!
http://lobid.org/oer/97162553-8719-4d1e-91f0-715d11992bd6#!
http://lobid.org/oer/b9d9e002-645e-4700-800a-b6f2b71bc004#!
http://lobid.org/oer/0c74896e-b2c9-41a0-9c22-259bf1ce2c63#!
```

**Comment by dr0i** [comment]
Thx for the report (actually, these are 3 issues):
1. two types:
   The data in the source is wrong. The wsis data says:
   
   "Schema:sameAs" : "http://lobid.org/oer/b9d9e002-645e-4700-800a-b6f2b71bc004#!",
    "dc:identifier" : "673352",
     "rdf:type" : "schema:Service"

while `http://lobid.org/oer/b9d9e002-645e-4700-800a-b6f2b71bc004#!` == ocw317 which is of type `Organization`.

1.a ) Not mentioned here, but a result of 1):
There are two geocoordinates, one of which comes from resource ocw371 (hardcoded in the data) and one comes from a reverse lookup made on wsis record. As part of #101 there is a fix so that Services will not have an address and no geocoordinate, this issue will be gone.
1. multiple links (two, exactly):
   these are also resulting because of having two resources interlinked via sameAs
   (but merged internally, only not the proper way ). The address should
   merge. Have to think about that how to do it. Should be solved because 77
   resources are affected.
2. lacking geo coordinates:
   Something like "Newton, MA" fails when doing geoname API lookup. I spoke about
   that topic with @acka47. Since there are only a handful of resources affected I
   would encourage to clean the data manually. I did this for the OCWC itself in the template , see 2383801.

**Comment by dr0i** [comment]
I just found that there are two geo coordinates for http://lobid.org/oer/b9d9e002-645e-4700-800a-b6f2b71bc004#! . I will fix this.

**Comment by literarymachine** [comment]
Yes. See my list above (https://github.com/hbz/oerworldmap/issues/105#issuecomment-40625699), which contains resources that have two geo coordinates.

**Comment by dr0i** [comment]
Fixed it.

**Comment by dr0i** [comment]
Regarding "multiple links to address" - this seems somehow already fixed.
For http://lobid.org/oer/b9d9e002-645e-4700-800a-b6f2b71bc004#! this is done because one of the two merged resources is of type Service, and Services are now forbidden to have an address.

But e.g. http://lobid.org/oer/5e3ca60f-f4a3-4dd0-8f1c-84e44ef5c844#! consists of two resources of which _both_ are typed as Organization. But the merged record has indeed only one address, as it should be.

I would want to close the issue and rather open a new one if one stumbles upon data regarding this special issue.

**Comment by literarymachine** [comment]
+1
