### ISSUE TITLE
Support any RDF on GET

### ISSUE THREAD

**Issue by fsteeg** [hbz/oerworldmap.prototype#48]

**Comment by fsteeg** [comment]
Deployed to staging. Samples:

`curl -H "Accept: text/plain" "http://staging.api.lobid.org/oer/1f4269a9-0103-4d9f-913c-5f127a5dab88"`

`curl -H "Accept: application/rdf+xml" "http://staging.api.lobid.org/oer?q=*&location=40.8,-86.6+40.8,-88.6+42.8,-88.6+42.8,-86.6"`

Assigning to @literarymachine for review.

**Comment by literarymachine** [comment]
This looks good. Really testing it in a Linked Data environment is hard though for the following reason (this is not the first time I encounter this).

Assume your example from above:

```
curl -H "Accept: text/plain" "http://staging.api.lobid.org/oer/1f4269a9-0103-4d9f-913c-5f127a5dab88#!"
```

This returns data not about the resource `<http://staging.api.lobid.org/oer/1f4269a9-0103-4d9f-913c-5f127a5dab88#!>`, but about `<http://lobid.org/oer/1f4269a9-0103-4d9f-913c-5f127a5dab88#!>`. Since in Linked Data URIs are not only used for retrieval, but also for identification, this is an important mismatch.

A possible solution could be to internally not use a fixed base-URI. I don't know the exact structure of your delivery process. But assuming that you process the RDF in some way before delivering it, you could internally use URIs such as `<1f4269a9-0103-4d9f-913c-5f127a5dab88#!>`and set the base to `<http://staging.api.lobid.org/oer/>` or `<http://lobid.org/oer/>` when delivering. I'm actually not sure if delivering data about `<1f4269a9-0103-4d9f-913c-5f127a5dab88#!>` from `http://staging.api.lobid.org/oer/` implicitly expands the URI so that a base URI would not even have to be set explicitly.

**Comment by dr0i** [comment]
So this is the same problem when http://lobid.org/person/118580604/about
describes in fact http://d-nb.info/gnd/118580604 ?

Is it not possible to treat these (non Linked Data-)URIs just as some uncool
non-linked-data URIs - while at the same time the harvested content (the RDF
that these non-ld-URIs provide) IS perfectly good linked data?

**Comment by literarymachine** [comment]
Again, this is a Linked Data vs. Lookup-API-Issue I believe. If I request a
Linked Data resource at http://staging.api.lobid.org/oer/foo#!, then I
expect information about that resource. This HTTP request pattern is
integral to Linked Data.

2014-03-21 14:19 GMT+01:00 Pascal Christoph notifications@github.com:

**Comment by literarymachine** [comment]
The above discussion probably belongs somewhere else.

+1 for the fix.

**Comment by fsteeg** [comment]
RDF on GET support deployed to production, closing.

`curl -H "Accept: text/plain" "http://lobid.org/oer/1f4269a9-0103-4d9f-913c-5f127a5dab88"`

Opened #55 for the issue raised in https://github.com/hbz/oerworldmap/issues/48#issuecomment-38262017
