### ISSUE TITLE
Supply exact URIs of geoname features

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap.prototype#81]
The `addressCountry` properties should contain the exact URIs of geonames features. Currently, the trailing slash is lacking, see e.g. [1]:

```
http://schema.org/addressCountry: [
    {
        @id: "http://sws.geonames.org/1814991"
    }
],
```

This should read:

```
http://schema.org/addressCountry: [
    {
        @id: "http://sws.geonames.org/1814991/"
    }
],
```

While data can also be received from the URL without the slash, the RDF contains statements only about the subject URI with slash.

[1] http://api.lobid.org/oer/7bf46009-c296-4c3d-91e9-55baab4d4362

**Comment by dr0i** [comment]
deployed to production, closing.

**Comment by literarymachine** [comment]
Some resources now contain an additional trailing slash, see http://lobid.org/oer?q=*&addressCountry:*//

**Comment by fsteeg** [comment]
Fixed in production: http://api.lobid.org/oer?q=%22Unisul%20Virtual%22 (used to be 2, one had the additional slash, now only one. Note your query still yields results for all `http://` occurences).

We thought the slash issue was already fixed, but the faulty documents were not replaced (the geonames ID is the parent for the OER resource, and Elasticsearch treats documents with identical IDs but different parents as separate documents).
