### ISSUE TITLE
Wrong label when lookup geonames

### ISSUE THREAD

**Issue by dr0i** [hbz/oerworldmap.prototype#91]
The labels of the countries seems to all to be English but "Belgium" is labeled as  i"ቤልጄም".

**Comment by literarymachine** [comment]
This is a known issue and basically expected behavior. The labels are not all in English, it is first tried to get the label in the language the browser is configured for. If that is not found, the default label (no language tag set) is used. If that is not found, the last label in the data is simply picked.

Note to myself: I am currently only looking into `gn:officialName`. A closer look at the geonames data revealed that `gn:alternateName` should also be taken into account to provide labels in the desired target language.

**Comment by literarymachine** [comment]
6a166d90f49c35b5cd569cd51a533da08f169584
